antvis/layout

package.json
src/layout/base.ts
src/layout/circular.ts
src/layout/comboForce.ts
src/layout/concentric.ts
src/layout/dagre.ts
src/layout/fruchterman.ts
src/layout/gpu/fruchterman.ts
src/layout/grid.ts
src/layout/mds.ts
src/layout/radial/radial.ts
src/layout/random.ts

feat: onLayoutEnd for every layout

feat: onLayoutEnd for every layout

---

src/layout/circular.ts
src/layout/comboForce.ts
src/layout/concentric.ts
src/layout/dagre.ts
src/layout/force/force.ts
src/layout/fruchterman.ts
src/layout/gForce.ts
src/layout/gpu/fruchterman.ts
src/layout/gpu/gForce.ts
src/layout/grid.ts
src/layout/mds.ts
src/layout/radial/radial.ts

fix: onLayoutEnd for one or none node

fix: onLayoutEnd for one or none node

---

package.json

chore: update webgpu

---

package.json
src/layout/dagre.ts
src/layout/types.ts

feat: compound for dagre

---

__tests__/g6/fa2-g6-test.ts
package.json
src/layout/forceAtlas2/body.ts
src/layout/forceAtlas2/index.ts
src/layout/forceAtlas2/quad.ts
src/layout/forceAtlas2/quadTree.ts
src/layout/index.ts
src/layout/types.ts

feat: force atlas 2

---

__tests__/g6/fa2-g6-test.ts
package.json
src/layout/gForce.ts

fix: gForce with descrete node with NaN result problem

fix: gForce with descrete node with NaN result problem

---

package.json
src/layout/comboForce.ts

fix: comboForce with chnageData problem

fix: comboForce with chnageData problem

---

src/layout/dagre.ts

PR Type:
* chore
PR Content：
* update notes

chore: update notes

---

package.json
src/layout/forceAtlas2/index.ts

fix: force atlas 2 default prune and barnesHut

fix: force atlas 2 default prune and barnesHut

---

src/layout/grid.ts

https://github.com/antvis/X6/issues/1193

fix: add return value for grid layout

---

package.json
src/layout/fruchterman.ts
src/layout/gForce.ts

fix: fruchterman and gforce with setinterval and webworker

fix: fruchterman and gforce with setinterval and webworker

---

package.json
src/layout/fruchterman.ts
src/layout/gForce.ts

fix: webworker onLayoutEnd problem

fix: webworker onLayoutEnd problem

---

package.json
src/layout/index.ts
src/layout/layout.ts
src/layout/types.ts

feat: export er layout

---

CHANGELOG.md
package.json
src/layout/comboForce.ts
src/layout/dagre/src/debug.ts
src/layout/dagre/src/position/bk.ts

fix: comboForce with unnecessary positions for combos; fix: dagre bug;

fix: comboForce with unnecessary positions for combos; fix: dagre bug;

---

CHANGELOG.md
package.json
src/layout/fruchterman.ts

fix: fruchterman without init clusterMap problem

fix: fruchterman without init clusterMap problem

---

CHANGELOG.md
package.json
src/layout/dagre.ts
src/layout/dagre/src/graphlib.ts

fix: array flat compatibility;

fix: array flat compatibility;

---

CHANGELOG.md
package.json
src/layout/dagre/src/graphlib.ts
src/layout/dagre/src/order/init-data-order.ts
src/layout/dagre/src/order/init-order.ts

fix: flat and reduce problem

---

CHANGELOG.md
package.json
src/layout/dagre/src/order/init-data-order.ts
src/layout/dagre/src/order/init-order.ts
src/layout/dagre/src/order/sort-subgraph.ts

fix: dagre error;

---

__tests__/g6/dagre-g6-test.ts
package.json
src/layout/comboCombined.ts
src/layout/dagre.ts

feat: dagre radial configuration

feat: dagre radial configuration

---

src/layout/dagre/src/layout.ts

修复antv/x6使用dargelayout时，attrs可能为undefined

fix(darge): 修复antv/x6使用dargelayout时出错

---

.gitignore
CHANGELOG.md
__tests__/g6/combo-concentric-test.ts
__tests__/g6/dagre-compound-g6-test.ts
__tests__/g6/dagre-g6-test.ts
__tests__/unit/dagreCompound.test.ts
package.json
src/constants.ts
src/layout/base.ts
src/layout/circular.ts
src/layout/comboCombined.ts
src/layout/comboForce.ts
src/layout/concentric.ts
src/layout/constants.ts
src/layout/dagre-compound.ts
src/layout/dagre.ts
src/layout/dagre/src/layout.ts
src/layout/dagre/src/order/cross-count.ts
src/layout/dagre/src/order/sort-subgraph.ts
src/layout/dagre/src/util.ts
src/layout/dagreCompound.ts
src/layout/fruchterman.ts
src/layout/gForce.ts
src/layout/grid.ts
src/layout/index.ts
src/layout/layout.ts
src/layout/radial/radial.ts
src/layout/types.ts
src/util/function.ts
src/util/math.ts

- feat: comboCombined layout;
- feat: add source and target node to the parameters of gForce linkDistance;
- feat: add hiddenNodes hiddenEdges hiddenCombos to the data of layout instance;

Combo concentric force

---

CHANGELOG.md
package.json
src/layout/gForce.ts

fix: gForce with same node positions

fix: gForce with same node positions

---

package.json

fixed https://github.com/ant-design/ant-design-charts/issues/786#issuecomment-1119563158

chore: add src into package

---

CHANGELOG.md
package.json
src/layout/comboCombined.ts
src/layout/types.ts

fix: comboCombined innerLayout with original node infos;
fix: DagreLayoutOptions with preset field;

fix: comboCombined innerLayout with original node infos; fix: DagreLayoutOptions with preset field;

---

CHANGELOG.md
package.json
src/layout/force2/index.ts
src/util/object.ts

perf: force2 with updated node mass

perf: force2 with updated node mass

---

CHANGELOG.md
package.json
src/util/gpu.ts
src/util/math.ts

fix: getAdjMatrix with inexistent source or target of edge;

fix: getAdjMatrix with inexistent source or target of edge;

---

CHANGELOG.md
package.json
src/layout/dagre/src/rank/util.ts

perf: improve the performance of dagre with layers;

perf: improve the performance of dagre with layers;

---

src/layout/dagre/src/layout.ts

fix: darge layer failed when two nodes are connected in two directions

---

CHANGELOG.md
package.json
src/layout/base.ts
src/layout/dagre.ts
src/layout/types.ts

fix: dagre layout for collapsed combos;

 fix: dagre layout for collapsed combos;

---

CHANGELOG.md
package.json

chore: update version and readme;

chore: update version and readme

---

CHANGELOG.md
package.json

chore: update version num

---

CHANGELOG.md
__tests__/g6/dagre-g6-test.ts
package.json
src/layout/dagre/src/rank/feasible-tree.ts
src/layout/dagre/src/rank/util.ts
src/layout/dagre/src/util.ts

fix: dagre with complex combos;

fix: dagre with complex combos;

---

CHANGELOG.md
package.json
src/layout/comboCombined.ts
src/util/math.ts

- perf: comboCombined with more accurate combined layout;

perf: comboCombined with more accurate combined layout;

---

packages/layout/src/Concentric.ts
packages/layout/src/Grid.ts
packages/layout/src/MDS.ts
packages/layout/src/Radial/index.ts
packages/layout/src/Radial/mds.ts
packages/layout/src/Radial/radialNonoverlapForce.ts
packages/layout/src/Random.ts
packages/layout/src/circular.ts
packages/layout/src/index.ts
packages/layout/src/types.ts
packages/layout/src/util/gpu.ts
packages/layout/src/util/math.ts

- chore: refine types;
- feat: add circular layout;
- feat: add grid layout;
- feat: add random layout;
- feat: add mds layout;
- feat: add concentric layout;
- feat: add radial layout;

chore: refine types and circular layout

---

package.json
packages/layout/package.json
packages/layout/src/circular.ts
packages/layout/src/concentric.ts
packages/layout/src/grid.ts
packages/layout/src/mds.ts
packages/layout/src/radial/index.ts
packages/layout/src/random.ts
packages/layout/src/types.ts
packages/layout/src/util/function.ts
packages/layout/src/util/object.ts

perf: read and format data

---

__tests__/unit/concentric.test.ts
demo/concentric.html
packages/layout/package.json
packages/layout/src/concentric.ts
packages/layout/src/grid.ts
packages/layout/src/supervisor.ts
packages/layout/src/types.ts
packages/layout/src/util/function.ts
packages/layout/src/util/object.ts

增加测试用例和 demo。
使用文档：https://observablehq.com/d/2db6b0cc5e97d8d6#cell-596

增加 concentric 布局测试用例和 demo

---

__tests__/unit/fruchterman.test.ts
demo/d3force.tick.html
demo/force.html
demo/force.tick.html
demo/fruchterman.html
demo/fruchterman.tick.html
demo/supervisor.concentric.html
demo/supervisor.d3force.html
demo/supervisor.force.html
demo/supervisor.fruchterman.html
packages/layout/package.json
packages/layout/src/circular.ts
packages/layout/src/concentric.ts
packages/layout/src/d3Force/index.ts
packages/layout/src/force/index.ts
packages/layout/src/fruchterman.ts
packages/layout/src/grid.ts
packages/layout/src/index.ts
packages/layout/src/mds.ts
packages/layout/src/radial/index.ts
packages/layout/src/random.ts
packages/layout/src/registry.ts
packages/layout/src/supervisor.ts
packages/layout/src/types.ts
packages/layout/src/util/object.ts
packages/layout/src/worker.ts

feat: add fruchterman layout and its test and demo

feat: add fruchterman layout and its test and demo

---

__tests__/unit/concentric.test.ts
__tests__/unit/forceAtlas2.test.ts
demo/forceAtlas2.html
demo/supervisor.forceAtlas2.html
package.json
packages/layout/package.json
packages/layout/src/circular.ts
packages/layout/src/concentric.ts
packages/layout/src/forceAtlas2/body.ts
packages/layout/src/forceAtlas2/index.ts
packages/layout/src/forceAtlas2/quad.ts
packages/layout/src/forceAtlas2/quadTree.ts
packages/layout/src/grid.ts
packages/layout/src/index.ts
packages/layout/src/mds.ts
packages/layout/src/radial/index.ts
packages/layout/src/registry.ts
packages/layout/src/types.ts
packages/layout/src/util/common.ts
packages/layout/src/util/object.ts

feat: add force atlas 2 layout and its test and demo; 
chore: util function for graph without nodes or graph with one node;

feat: add force atlas 2 layout and its test and demo

---

CHANGELOG.md
package.json
src/layout/dagre.ts

fix: error edge controlPoints in dagre with layer assignment;

fix: error edge controlPoints in dagre with layer assignment;

---

package.json
src/layout/dagre/src/layout.ts
src/layout/dagre/src/order/index.ts
src/layout/dagre/src/order/init-data-order.ts
src/layout/dagre/src/order/sort-subgraph.ts
src/layout/dagre/src/order/sort.ts

fix: node order is not fixed when keepNodeOrder is true in dagre

fix: node order is not fixed when keepNodeOrder is true in dagre

---

CHANGELOG.md
package.json
src/layout/dagre/src/order/sort.ts

fix: fix node order problem of dagre;

fix: fix node order problem of dagre;

---

CHANGELOG.md
jest.config.js
package.json
src/layout/comboCombined.ts
src/layout/dagre.ts
src/layout/dagre/src/position/bk.ts
src/layout/dagre/src/rank/feasible-tree.ts
src/layout/dagre/src/rank/util.ts

fix: controlPoints problem in dagre with layer in data;

fix: controlPoints problem in dagre with layer in data;

---

CHANGELOG.md
package.json
src/layout/force2/index.ts

feat: force2 supports attractive forces to the top and bottom

feat: force2 supports attractive forces to the top and bottom

---

CHANGELOG.md
package.json
src/layout/comboCombined.ts

fix: comboCombined node size problem;

fix: comboCombined node size problem;

---

packages/layout/package.json
packages/layout/src/concentric.ts
packages/layout/src/dagre.ts
packages/layout/src/dagre/add-border-segments.ts
packages/layout/src/dagre/layout.ts
packages/layout/src/dagre/nesting-graph.ts
packages/layout/src/dagre/order/add-subgraph-constraints.ts
packages/layout/src/dagre/order/build-layer-graph.ts
packages/layout/src/dagre/order/init-data-order.ts
packages/layout/src/dagre/order/init-order.ts
packages/layout/src/dagre/order/sort-subgraph.ts
packages/layout/src/dagre/parent-dummy-chains.ts
packages/layout/src/dagre/util.ts
packages/layout/src/force/forceNBody.ts
packages/layout/src/force/index.ts
packages/layout/src/supervisor.ts
packages/layout/src/types.ts
packages/layout/src/util/function.ts

feat: dagre with combo;
fix: force layout with overlapping problem

feat: dagre with combo; fix: force layout with overlapping problem

---

.github/workflows/build.yml
README.md

chore: update readme badge

---

packages/layout/package.json
packages/layout/src/force/index.ts

chore: format and refine dagre code

chore: format and refine dagre code

---

packages/layout/package.json
packages/layout/src/util/function.ts

fix: circular dependent

---

packages/layout/package.json
packages/layout/src/dagre.ts
packages/layout/src/dagre/layout.ts
packages/layout/src/types.ts

feat: dagre supports preset

---

packages/layout/package.json
packages/layout/src/dagre.ts
packages/layout/src/types.ts

feat: dagre supports ranker configuration

feat: dagre supports ranker configuration

---

src/layout/dagre.ts

add some edge properties the edgeLabelSpace config needs

fix: enable edgeLabelSpace config

---

packages/layout/src/dagre/position/index.ts

项目存在两种展示模式，一种是配置的，一种是使用数据的，两种展示的内容不同会导致节点高度不同，在不同节点高度使用Degre布局时positiony计算使得两节点间距不等。
```json
{
"nodes": [
{
"shape": "vue-base-node",
"zIndex": 2,
"_order": 0,
"id": "0a206645-f545-47f9-8e78-fdc025bff3d2",
"width": 280,
"height": 130,
"size": {
"width": 280,
"height": 130
}
},
{
"shape": "vue-base-node",
"zIndex": 3,
"_order": 0,
"id": "03a716f8-fc27-4207-b967-686c0e86f7bf",
"width": 280,
"height": 226,
"size": {
"width": 280,
"height": 226
}
},
{
"shape": "vue-base-node",
"zIndex": 1,
"_order": 0,
"id": "be764037-ba8a-4846-826a-a03236a7c4b1",
"width": 280,
"height": 130,
"size": {
"width": 280,
"height": 130
}
}
],
"edges": [
{
"shape": "edge",
"defaultLabel": {
"markup": {
"tagName": "foreignObject",
"selector": "fo",
"children": [
{
"ns": "http://www.w3.org/1999/xhtml",
"tagName": …
```

feat:修复使用Degre布局TB方向,节点高度不同导致间距不一致问题

---

packages/layout/src/dagre/position/index.ts

Revert "feat:修复使用Degre布局TB方向,节点高度不同导致间距不一致问题"

---

packages/layout/package.json
packages/layout/src/d3-force-3d/types.ts
packages/layout/src/d3-force/index.ts
packages/layout/src/d3-force/types.ts

* D3 Force 和 D3 Force 3D 支持 setFixedPosition API，用于在迭代过程中固定节点位置
* 支持通过配置为 false 来关闭部分力的配置
```jsonc
{
"center": false // 关闭内置的中心力
}
```

refactor: force layout support setFixedPosition API

---

packages/layout-gpu/package.json
packages/layout-gpu/src/fruchterman.ts
packages/layout-gpu/src/gforce.ts
packages/layout-rust/Cargo.lock
packages/layout-rust/src/lib.rs
packages/layout-wasm/Cargo.lock
packages/layout-wasm/package.json
packages/layout-wasm/src/dagre.ts
packages/layout-wasm/src/force.ts
packages/layout-wasm/src/forceatlas2.ts
packages/layout-wasm/src/fruchterman.ts
packages/layout/package.json
packages/layout/src/concentric.ts
packages/layout/src/force/index.ts
packages/layout/src/forceAtlas2/index.ts
packages/layout/src/fruchterman.ts
packages/layout/src/grid.ts
packages/layout/src/mds.ts
packages/layout/src/radial/index.ts
packages/layout/src/random.ts

* 修复异步的 assign 方法调用
* 更新 wasm/rust 包依赖

fix: fix async assign invoke
